from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage
from dotenv import load_dotenv
load_dotenv()

def run_writer(company: str, analysis: str) -> str:
    llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.3)
    print("\n[WRITER] Drafting report...")

    response = llm.invoke([
        HumanMessage(content=f"""You are a senior business report writer.

Write a professional Competitive Intelligence Report in clean Markdown for: {company}

Use this exact structure:

# Competitive Intelligence Report: {company}
*Generated by CompeteAI Multi-Agent System*

## Executive Summary
(3-4 sentences — key takeaway for a busy executive)

## Company Overview
(founding, product, business model, scale)

## SWOT Analysis
| | Positive | Negative |
|---|---|---|
| Internal | Strengths | Weaknesses |
| External | Opportunities | Threats |

(fill in the table with bullet points in each cell)

## Market Position
(where they sit in the competitive landscape)

## Technology and Innovation
(tech stack, AI usage, differentiators)

## Risk Assessment
(top risks with likelihood and impact)

## Strategic Recommendation
> **Verdict:** [Partner / Compete Directly / Monitor / Avoid]

(2-3 sentences justifying the recommendation)

---
*Report scored and approved by CompeteAI Critic Agent*

Analysis data:
{analysis}""")
    ])

    return response.content